spring:
  datasource:
    url: jdbc:h2:mem:car_management_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  modulith:
    events:
      republish-outstanding-events-on-restart: true

server:
  port: 8088